# Generated by Django 6.0.3 on 2026-03-10 20:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuildingType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, default="🏗️", max_length=50)),
                ("cost", models.PositiveIntegerField(default=50, help_text="Unit cost to build")),
                ("build_time_ticks", models.PositiveIntegerField(default=10, help_text="Ticks to complete building")),
                (
                    "max_per_region",
                    models.PositiveIntegerField(default=1, help_text="Max buildings of this type per region"),
                ),
                ("requires_coastal", models.BooleanField(default=False, help_text="Only buildable in coastal regions")),
                (
                    "defense_bonus",
                    models.FloatField(default=0.0, help_text="Defense bonus for region (e.g. 0.2 = 20%)"),
                ),
                ("vision_range", models.PositiveIntegerField(default=0, help_text="Extra vision range in regions")),
                ("unit_generation_bonus", models.FloatField(default=0.0, help_text="Extra units generated per tick")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="GameSettings",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("max_players", models.PositiveIntegerField(default=2, help_text="Maximum players per match")),
                ("min_players", models.PositiveIntegerField(default=2, help_text="Minimum players to start match")),
                (
                    "tick_interval_ms",
                    models.PositiveIntegerField(default=1000, help_text="Game tick interval in milliseconds"),
                ),
                (
                    "capital_selection_time_seconds",
                    models.PositiveIntegerField(default=30, help_text="Time to select capital"),
                ),
                (
                    "match_duration_limit_minutes",
                    models.PositiveIntegerField(default=60, help_text="Max match duration (0=unlimited)"),
                ),
                (
                    "base_unit_generation_rate",
                    models.FloatField(default=1.0, help_text="Units generated per tick per region"),
                ),
                ("capital_generation_bonus", models.FloatField(default=2.0, help_text="Multiplier for capital region")),
                ("attacker_advantage", models.FloatField(default=0.0, help_text="Bonus for attacker (e.g. 0.1 = 10%)")),
                ("defender_advantage", models.FloatField(default=0.1, help_text="Bonus for defender (e.g. 0.1 = 10%)")),
                ("combat_randomness", models.FloatField(default=0.2, help_text="Random factor in combat (0-1)")),
                ("starting_units", models.PositiveIntegerField(default=10, help_text="Units in capital at start")),
                ("starting_regions", models.PositiveIntegerField(default=1, help_text="Number of starting regions")),
                ("elo_k_factor", models.PositiveIntegerField(default=32, help_text="K-factor for ELO calculation")),
            ],
            options={
                "verbose_name": "Game Settings",
                "verbose_name_plural": "Game Settings",
            },
        ),
        migrations.CreateModel(
            name="MapConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "country_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of ISO country codes to include. Empty = all countries.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UnitType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, default="⚔️", max_length=50)),
                ("attack", models.FloatField(default=1.0)),
                ("defense", models.FloatField(default=1.0)),
                ("speed", models.PositiveIntegerField(default=1, help_text="Regions moved per tick")),
                ("attack_range", models.PositiveIntegerField(default=1, help_text="Attack range in regions")),
                ("production_cost", models.PositiveIntegerField(default=5, help_text="Unit cost to produce")),
                ("production_time_ticks", models.PositiveIntegerField(default=5, help_text="Ticks to produce")),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("land", "Land"), ("sea", "Sea"), ("air", "Air")], default="land", max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "produced_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Building required to produce this unit (null=default unit)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_types",
                        to="game_config.buildingtype",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
