# Generated by Django 6.0.3 on 2026-03-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_config", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesettings",
            name="neutral_region_units",
            field=models.PositiveIntegerField(default=3, help_text="Garrison units in unowned (neutral) regions"),
        ),
    ]
