# Generated by Django 6.0.3 on 2026-03-11 00:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game_config", "0002_gamesettings_neutral_region_units"),
        ("game_config", "0002_mapconfig_min_capital_distance"),
    ]

    operations = []
