# Generated by Django 6.0.3 on 2026-03-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_config", "0003_merge_20260311_0019"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingtype",
            name="asset_key",
            field=models.SlugField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="unittype",
            name="asset_key",
            field=models.SlugField(blank=True, default="", max_length=100),
        ),
    ]
