# Generated by Django 6.0.3 on 2026-03-12 20:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_config", "0009_gamemode"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbilityType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("asset_key", models.SlugField(blank=True, default="", max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                ("sound_key", models.CharField(blank=True, default="", max_length=100)),
                (
                    "target_type",
                    models.CharField(
                        choices=[("enemy", "Enemy"), ("own", "Own"), ("any", "Any")], default="enemy", max_length=10
                    ),
                ),
                ("range", models.PositiveIntegerField(default=1, help_text="Max hops from owned regions to target")),
                ("currency_cost", models.PositiveIntegerField(default=50, help_text="Currency cost to use")),
                ("cooldown_ticks", models.PositiveIntegerField(default=60, help_text="Cooldown in ticks after use")),
                ("damage", models.PositiveIntegerField(default=0, help_text="Instant damage (units killed)")),
                (
                    "effect_duration_ticks",
                    models.PositiveIntegerField(default=0, help_text="Duration for persistent effects"),
                ),
                (
                    "effect_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-ability params: production_reduction, unit_kill_percent, spread_range, collect_percent",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
