# Generated by Django 6.0.3 on 2026-03-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_config", "0015_add_unittype_level_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="abilitytype",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Custom ability image (overrides frontend default)",
                null=True,
                upload_to="game_assets/abilities/",
            ),
        ),
        migrations.AddField(
            model_name="abilitytype",
            name="sound",
            field=models.FileField(
                blank=True,
                help_text="Custom ability sound (overrides frontend default)",
                null=True,
                upload_to="game_assets/sounds/",
            ),
        ),
        migrations.AddField(
            model_name="buildingtype",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Custom building image (overrides frontend default)",
                null=True,
                upload_to="game_assets/buildings/",
            ),
        ),
        migrations.AddField(
            model_name="unittype",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Custom unit image (overrides frontend default)",
                null=True,
                upload_to="game_assets/units/",
            ),
        ),
    ]
