from django.db import migrations


SYSTEM_MODULES = [
    {
        'slug': 'auth',
        'name': 'Authentication',
        'description': 'Core authentication system (JWT login/logout). Cannot be disabled.',
        'icon': 'lock',
        'enabled': True,
        'is_core': True,
        'affects_backend': True,
        'affects_frontend': True,
        'affects_gateway': False,
        'order': 1,
        'config': {},
        'config_schema': [],
    },
    {
        'slug': 'registration',
        'name': 'Registration',
        'description': 'New user registration. Disable to close registrations.',
        'icon': 'person_add',
        'enabled': True,
        'is_core': False,
        'affects_backend': True,
        'affects_frontend': True,
        'affects_gateway': False,
        'order': 2,
        'config': {},
        'config_schema': [],
    },
    {
        'slug': 'social-auth',
        'name': 'Social Authentication',
        'description': 'Login/register via Google, Discord, and other OAuth providers.',
        'icon': 'share',
        'enabled': True,
        'is_core': False,
        'affects_backend': True,
        'affects_frontend': True,
        'affects_gateway': False,
        'order': 3,
        'config': {},
        'config_schema': [],
    },
    {
        'slug': 'matchmaking',
        'name': 'Matchmaking',
        'description': 'Match queue, lobbies, and game creation. Disabling prevents new matches.',
        'icon': 'groups',
        'enabled': True,
        'is_core': False,
        'affects_backend': True,
        'affects_frontend': True,
        'affects_gateway': True,
        'order': 10,
        'config': {},
        'config_schema': [],
    },
    {
        'slug': 'tutorial',
        'name': 'Tutorial',
        'description': 'Interactive tutorial with AI opponent for new players.',
        'icon': 'school',
        'enabled': True,
        'is_core': False,
        'affects_backend': True,
        'affects_frontend': True,
        'affects_gateway': True,
        'order': 11,
        'config': {},
        'config_schema': [],
    },
    {
        'slug': 'bots',
        'name': 'AI Bots',
        'description': 'AI-controlled opponents to fill matches. Disable for PvP-only.',
        'icon': 'smart_toy',
        'enabled': True,
        'is_core': False,
        'affects_backend': False,
        'affects_frontend': False,
        'affects_gateway': True,
        'order': 12,
        'config': {},
        'config_schema': [],
    },
    {
        'slug': 'chat',
        'name': 'Chat',
        'description': 'In-game chat and match chat messages.',
        'icon': 'chat',
        'enabled': True,
        'is_core': False,
        'affects_backend': True,
        'affects_frontend': True,
        'affects_gateway': True,
        'order': 13,
        'config': {},
        'config_schema': [],
    },
    {
        'slug': 'voice-chat',
        'name': 'Voice Chat',
        'description': 'In-game voice communication via LiveKit.',
        'icon': 'mic',
        'enabled': True,
        'is_core': False,
        'affects_backend': False,
        'affects_frontend': True,
        'affects_gateway': True,
        'order': 14,
        'config': {},
        'config_schema': [],
    },
    {
        'slug': 'anticheat',
        'name': 'Anti-Cheat',
        'description': 'Behavioral analysis, action flood detection, and match integrity protection.',
        'icon': 'shield',
        'enabled': True,
        'is_core': False,
        'affects_backend': True,
        'affects_frontend': False,
        'affects_gateway': True,
        'order': 15,
        'config': {
            'auto_ban_enabled': False,
            'max_violations_before_flag': 5,
        },
        'config_schema': [
            {'key': 'auto_ban_enabled', 'label': 'Auto-ban on excessive violations', 'type': 'bool', 'default': False},
            {'key': 'max_violations_before_flag', 'label': 'Max violations before flagging', 'type': 'int', 'default': 5, 'min': 1, 'max': 50},
        ],
    },
    {
        'slug': 'replay',
        'name': 'Replay System',
        'description': 'Match replay viewing and sharing.',
        'icon': 'replay',
        'enabled': True,
        'is_core': False,
        'affects_backend': True,
        'affects_frontend': True,
        'affects_gateway': False,
        'order': 20,
        'config': {},
        'config_schema': [],
    },
    {
        'slug': 'leaderboard',
        'name': 'Leaderboard',
        'description': 'ELO rankings and player leaderboards.',
        'icon': 'leaderboard',
        'enabled': True,
        'is_core': False,
        'affects_backend': True,
        'affects_frontend': True,
        'affects_gateway': False,
        'order': 21,
        'config': {},
        'config_schema': [],
    },
    {
        'slug': 'inventory',
        'name': 'Inventory',
        'description': 'Player inventory, wallets, item drops, and item management.',
        'icon': 'inventory_2',
        'enabled': True,
        'is_core': False,
        'affects_backend': True,
        'affects_frontend': True,
        'affects_gateway': False,
        'order': 30,
        'config': {},
        'config_schema': [],
    },
    {
        'slug': 'cosmetics',
        'name': 'Cosmetics & Decks',
        'description': 'Cosmetic items, equipped skins, and deck management.',
        'icon': 'palette',
        'enabled': True,
        'is_core': False,
        'affects_backend': True,
        'affects_frontend': True,
        'affects_gateway': False,
        'order': 31,
        'config': {},
        'config_schema': [],
    },
    {
        'slug': 'shop',
        'name': 'Shop',
        'description': 'In-game item shop with categories.',
        'icon': 'storefront',
        'enabled': True,
        'is_core': False,
        'affects_backend': True,
        'affects_frontend': True,
        'affects_gateway': False,
        'order': 32,
        'config': {},
        'config_schema': [],
    },
    {
        'slug': 'marketplace',
        'name': 'Marketplace',
        'description': 'Player-to-player item trading and listings.',
        'icon': 'store',
        'enabled': True,
        'is_core': False,
        'affects_backend': True,
        'affects_frontend': True,
        'affects_gateway': False,
        'order': 33,
        'config': {},
        'config_schema': [],
    },
    {
        'slug': 'crafting',
        'name': 'Crafting',
        'description': 'Item crafting with recipes and ingredients.',
        'icon': 'construction',
        'enabled': True,
        'is_core': False,
        'affects_backend': True,
        'affects_frontend': True,
        'affects_gateway': False,
        'order': 34,
        'config': {},
        'config_schema': [],
    },
    {
        'slug': 'developers',
        'name': 'Developer API',
        'description': 'Third-party developer portal, API keys, OAuth apps, and webhooks.',
        'icon': 'code',
        'enabled': True,
        'is_core': False,
        'affects_backend': True,
        'affects_frontend': True,
        'affects_gateway': False,
        'order': 40,
        'config': {},
        'config_schema': [],
    },
]


def seed_system_modules(apps, schema_editor):
    SystemModule = apps.get_model('game_config', 'SystemModule')
    for data in SYSTEM_MODULES:
        SystemModule.objects.update_or_create(
            slug=data['slug'],
            defaults=data,
        )


def unseed_system_modules(apps, schema_editor):
    SystemModule = apps.get_model('game_config', 'SystemModule')
    SystemModule.objects.filter(slug__in=[m['slug'] for m in SYSTEM_MODULES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game_config', '0022_system_module'),
    ]

    operations = [
        migrations.RunPython(seed_system_modules, unseed_system_modules),
    ]
