# Generated by Django 6.0.3 on 2026-03-18 17:43

import django.db.models.deletion
from django.db import migrations, models


def migrate_gamemodule_to_systemmodule(apps, schema_editor):
    """Copy GameModule data into SystemModule, then remap override FKs."""
    GameModule = apps.get_model("game_config", "GameModule")
    SystemModule = apps.get_model("game_config", "SystemModule")
    GameSettingsModuleOverride = apps.get_model("game_config", "GameSettingsModuleOverride")
    GameModeModuleOverride = apps.get_model("game_config", "GameModeModuleOverride")

    # Step 1: Copy each GameModule into SystemModule
    slug_to_sysmodule = {}
    for gm in GameModule.objects.all():
        sm, _ = SystemModule.objects.update_or_create(
            slug=gm.slug,
            defaults={
                "name": gm.name,
                "description": gm.description,
                "icon": gm.icon,
                "module_type": "game",
                "enabled": True,
                "config": {},
                "config_schema": gm.config_schema,
                "affects_backend": True,
                "affects_frontend": True,
                "affects_gateway": True,
                "is_core": False,
                "order": gm.order + 100,  # offset to avoid collisions with existing system modules
                "default_enabled": gm.default_enabled,
                "default_config": gm.default_config,
                "field_mapping": gm.field_mapping,
            },
        )
        slug_to_sysmodule[gm.id] = sm.id

    # Step 2: Remap override FKs from GameModule ID to SystemModule ID
    for override in GameSettingsModuleOverride.objects.all():
        new_id = slug_to_sysmodule.get(override.module_id)
        if new_id:
            override.new_module_id = new_id
            override.save(update_fields=["new_module_id"])

    for override in GameModeModuleOverride.objects.all():
        new_id = slug_to_sysmodule.get(override.module_id)
        if new_id:
            override.new_module_id = new_id
            override.save(update_fields=["new_module_id"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("game_config", "0024_enrich_system_module_configs"),
    ]

    operations = [
        # 1. Add new fields to SystemModule
        migrations.AddField(
            model_name="systemmodule",
            name="default_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Default config parameters for game modules (merged with overrides per match)",
            ),
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="default_enabled",
            field=models.BooleanField(default=True, help_text="Default enabled state for new matches"),
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="field_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Maps module to flat settings fields: {"enabled_field": "weather_enabled", "config_fields": {"key": "snapshot_field"}}',
            ),
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Whether this module is available in the system"),
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="module_type",
            field=models.CharField(
                choices=[("system", "System"), ("game", "Game")],
                default="system",
                help_text="System = app-wide feature toggle, Game = per-match configurable module",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="is_core",
            field=models.BooleanField(default=False, help_text="Core modules cannot be disabled (auth, config, geo)"),
        ),
        # 2. Add temporary new_module FK on overrides (nullable, pointing to SystemModule)
        migrations.AddField(
            model_name="gamesettingsmoduleoverride",
            name="new_module",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="game_config.systemmodule",
            ),
        ),
        migrations.AddField(
            model_name="gamemodemoduleoverride",
            name="new_module",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="game_config.systemmodule",
            ),
        ),
        # 3. Data migration: copy GameModule -> SystemModule, remap override FKs
        migrations.RunPython(migrate_gamemodule_to_systemmodule, noop),
        # 4. Drop unique_together before removing the old FK (required for SQLite)
        migrations.AlterUniqueTogether(
            name="gamesettingsmoduleoverride",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="gamemodemoduleoverride",
            unique_together=set(),
        ),
        # 4b. Remove old module FK (to GameModule)
        migrations.RemoveField(
            model_name="gamesettingsmoduleoverride",
            name="module",
        ),
        migrations.RemoveField(
            model_name="gamemodemoduleoverride",
            name="module",
        ),
        # 5. Rename new_module -> module
        migrations.RenameField(
            model_name="gamesettingsmoduleoverride",
            old_name="new_module",
            new_name="module",
        ),
        migrations.RenameField(
            model_name="gamemodemoduleoverride",
            old_name="new_module",
            new_name="module",
        ),
        # 6. Make module non-nullable and set proper related_name
        migrations.AlterField(
            model_name="gamesettingsmoduleoverride",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings_overrides",
                to="game_config.systemmodule",
            ),
        ),
        migrations.AlterField(
            model_name="gamemodemoduleoverride",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mode_overrides",
                to="game_config.systemmodule",
            ),
        ),
        # 7. Re-add unique_together constraints
        migrations.AlterUniqueTogether(
            name="gamesettingsmoduleoverride",
            unique_together={("game_settings", "module")},
        ),
        migrations.AlterUniqueTogether(
            name="gamemodemoduleoverride",
            unique_together={("game_mode", "module")},
        ),
        # 8. Delete GameModule model
        migrations.DeleteModel(
            name="GameModule",
        ),
    ]
