# Generated by Django 6.0.3 on 2026-03-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_config', '0028_add_ticks_per_hop_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingtype',
            name='build_time_ticks',
        ),
        migrations.RemoveField(
            model_name='buildingtype',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='buildingtype',
            name='energy_cost',
        ),
        migrations.RemoveField(
            model_name='unittype',
            name='manpower_cost',
        ),
        migrations.RemoveField(
            model_name='unittype',
            name='production_cost',
        ),
        migrations.RemoveField(
            model_name='unittype',
            name='production_time_ticks',
        ),
    ]
