# Generated by Django 6.0.3 on 2026-03-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_config', '0031_gamemode_proposal_timeout_ticks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemode',
            name='ap_cost_ability',
            field=models.IntegerField(default=4, help_text='AP cost for ability use'),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='ap_cost_attack',
            field=models.IntegerField(default=3, help_text='AP cost for attack/bombard/intercept'),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='ap_cost_build',
            field=models.IntegerField(default=2, help_text='AP cost for build/upgrade'),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='ap_cost_move',
            field=models.IntegerField(default=2, help_text='AP cost for move'),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='ap_cost_produce',
            field=models.IntegerField(default=1, help_text='AP cost for unit production'),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='ap_regen_interval',
            field=models.IntegerField(default=3, help_text='Ticks between each +1 AP regeneration'),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='fatigue_attack_modifier',
            field=models.FloatField(default=0.3, help_text='Power reduction after winning attack (e.g. 0.30 = 30%)'),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='fatigue_attack_ticks',
            field=models.IntegerField(default=5, help_text='Duration of attacker fatigue in ticks'),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='fatigue_defense_modifier',
            field=models.FloatField(default=0.2, help_text='Power reduction after winning defense (e.g. 0.20 = 20%)'),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='fatigue_defense_ticks',
            field=models.IntegerField(default=3, help_text='Duration of defender fatigue in ticks'),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='max_action_points',
            field=models.IntegerField(default=10, help_text='Max AP pool per player'),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='region_attack_cooldown',
            field=models.IntegerField(default=5, help_text='Ticks before a region can attack again'),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='region_move_cooldown',
            field=models.IntegerField(default=2, help_text='Ticks before a region can move again'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='ap_cost_ability',
            field=models.IntegerField(default=4, help_text='AP cost for ability use'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='ap_cost_attack',
            field=models.IntegerField(default=3, help_text='AP cost for attack/bombard/intercept'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='ap_cost_build',
            field=models.IntegerField(default=2, help_text='AP cost for build/upgrade'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='ap_cost_move',
            field=models.IntegerField(default=2, help_text='AP cost for move'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='ap_cost_produce',
            field=models.IntegerField(default=1, help_text='AP cost for unit production'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='ap_regen_interval',
            field=models.IntegerField(default=3, help_text='Ticks between each +1 AP regeneration'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='fatigue_attack_modifier',
            field=models.FloatField(default=0.3, help_text='Power reduction after winning attack (e.g. 0.30 = 30%)'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='fatigue_attack_ticks',
            field=models.IntegerField(default=5, help_text='Duration of attacker fatigue in ticks'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='fatigue_defense_modifier',
            field=models.FloatField(default=0.2, help_text='Power reduction after winning defense (e.g. 0.20 = 20%)'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='fatigue_defense_ticks',
            field=models.IntegerField(default=3, help_text='Duration of defender fatigue in ticks'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='max_action_points',
            field=models.IntegerField(default=10, help_text='Max AP pool per player'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='region_attack_cooldown',
            field=models.IntegerField(default=5, help_text='Ticks before a region can attack again'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='region_move_cooldown',
            field=models.IntegerField(default=2, help_text='Ticks before a region can move again'),
        ),
    ]
