# Generated by Django 6.0.3 on 2026-03-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_config', '0033_remove_attack_cooldown_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemode',
            name='ap_cost_ability',
            field=models.IntegerField(default=3, help_text='AP cost for ability use'),
        ),
        migrations.AlterField(
            model_name='gamemode',
            name='ap_cost_attack',
            field=models.IntegerField(default=4, help_text='Max AP cost for attack/bombard/intercept (scaled by % units sent)'),
        ),
        migrations.AlterField(
            model_name='gamemode',
            name='ap_cost_build',
            field=models.IntegerField(default=1, help_text='AP cost for build/upgrade'),
        ),
        migrations.AlterField(
            model_name='gamemode',
            name='ap_cost_move',
            field=models.IntegerField(default=1, help_text='AP cost for move'),
        ),
        migrations.AlterField(
            model_name='gamemode',
            name='ap_cost_produce',
            field=models.IntegerField(default=0, help_text='AP cost for unit production'),
        ),
        migrations.AlterField(
            model_name='gamemode',
            name='ap_regen_interval',
            field=models.IntegerField(default=2, help_text='Ticks between each +1 AP regeneration'),
        ),
        migrations.AlterField(
            model_name='gamemode',
            name='max_action_points',
            field=models.IntegerField(default=15, help_text='Max AP pool per player'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='ap_cost_ability',
            field=models.IntegerField(default=3, help_text='AP cost for ability use'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='ap_cost_attack',
            field=models.IntegerField(default=4, help_text='Max AP cost for attack/bombard/intercept (scaled by % units sent)'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='ap_cost_build',
            field=models.IntegerField(default=1, help_text='AP cost for build/upgrade'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='ap_cost_move',
            field=models.IntegerField(default=1, help_text='AP cost for move'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='ap_cost_produce',
            field=models.IntegerField(default=0, help_text='AP cost for unit production'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='ap_regen_interval',
            field=models.IntegerField(default=2, help_text='Ticks between each +1 AP regeneration'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='max_action_points',
            field=models.IntegerField(default=15, help_text='Max AP pool per player'),
        ),
    ]
