# Generated by Django 6.0.3 on 2026-03-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_is_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tutorial_completed",
            field=models.BooleanField(default=False),
        ),
    ]
