# Generated by Django 6.0.3 on 2026-03-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_tutorial_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="banned_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
