# Generated by Django 6.0.3 on 2026-03-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_directmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialaccount",
            name="provider",
            field=models.CharField(
                choices=[("google", "Google"), ("discord", "Discord"), ("steam", "Steam")], max_length=20
            ),
        ),
    ]
