# Generated by Django 6.0.3 on 2026-03-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_socialaccount_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLevel',
            fields=[
                ('level', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('experience_required', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=50)),
                ('perks', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
