# Generated by Django 6.0.3 on 2026-03-14 10:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "transaction_fee_percent",
                    models.FloatField(default=5.0, help_text="Fee % taken from seller on sale"),
                ),
                (
                    "listing_duration_hours",
                    models.PositiveIntegerField(default=72, help_text="Default listing duration"),
                ),
                ("max_active_listings_per_user", models.PositiveIntegerField(default=20)),
                (
                    "bot_restock_interval_minutes",
                    models.PositiveIntegerField(default=60, help_text="How often bot restocks"),
                ),
                (
                    "bot_price_variance_percent",
                    models.FloatField(default=15.0, help_text="Bot price random variance %"),
                ),
            ],
            options={
                "verbose_name": "marketplace config",
                "verbose_name_plural": "marketplace config",
            },
        ),
        migrations.CreateModel(
            name="MarketListing",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "listing_type",
                    models.CharField(choices=[("sell", "Sell Order"), ("buy", "Buy Order")], max_length=10),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price_per_unit", models.PositiveIntegerField(help_text="Gold per unit")),
                ("quantity_remaining", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_bot_listing", models.BooleanField(default=False, help_text="Created by bot seeder")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="market_listings", to="inventory.item"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField()),
                ("price_per_unit", models.PositiveIntegerField()),
                ("total_price", models.PositiveIntegerField()),
                ("fee", models.PositiveIntegerField(default=0, help_text="Transaction fee (gold sink)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="inventory.item"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="marketplace.marketlisting",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="marketlisting",
            index=models.Index(fields=["item", "listing_type", "status"], name="marketplace_item_id_297b4a_idx"),
        ),
        migrations.AddIndex(
            model_name="marketlisting",
            index=models.Index(fields=["status", "expires_at"], name="marketplace_status_022ede_idx"),
        ),
    ]
