# Generated by Django 6.0.3 on 2026-03-23 22:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matchmaking", "0008_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClanLevel",
            fields=[
                ("level", models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ("experience_required", models.PositiveIntegerField()),
                ("max_members", models.PositiveIntegerField()),
                ("treasury_cap", models.PositiveIntegerField()),
                ("perks", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="Clan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=32, unique=True)),
                ("tag", models.CharField(max_length=5, unique=True)),
                ("description", models.TextField(blank=True, default="", max_length=500)),
                ("badge", models.ImageField(blank=True, upload_to="clans/badges/")),
                ("color", models.CharField(default="#FFFFFF", max_length=7)),
                ("level", models.PositiveIntegerField(default=1)),
                ("experience", models.PositiveIntegerField(default=0)),
                ("elo_rating", models.IntegerField(default=1000)),
                ("max_members", models.PositiveIntegerField(default=10)),
                ("is_recruiting", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                ("treasury_gold", models.PositiveIntegerField(default=0)),
                ("tax_percent", models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("dissolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="led_clans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClanChatMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("content", models.TextField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "clan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="chat_messages", to="clans.clan"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clan_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClanWar",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("finished", "Finished"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("challenger_elo_change", models.IntegerField(default=0)),
                ("defender_elo_change", models.IntegerField(default=0)),
                ("players_per_side", models.PositiveIntegerField(default=3)),
                ("wager_gold", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "challenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="wars_as_challenger", to="clans.clan"
                    ),
                ),
                (
                    "defender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="wars_as_defender", to="clans.clan"
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clan_war",
                        to="matchmaking.match",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wars_won",
                        to="clans.clan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClanWarParticipant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "clan",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="clans.clan"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clan_war_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "war",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="clans.clanwar"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClanActivityLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("member_joined", "Member Joined"),
                            ("member_left", "Member Left"),
                            ("member_kicked", "Member Kicked"),
                            ("member_promoted", "Member Promoted"),
                            ("member_demoted", "Member Demoted"),
                            ("gold_donated", "Gold Donated"),
                            ("gold_withdrawn", "Gold Withdrawn"),
                            ("settings_changed", "Settings Changed"),
                            ("war_declared", "War Declared"),
                            ("war_won", "War Won"),
                            ("war_lost", "War Lost"),
                            ("clan_leveled_up", "Clan Leveled Up"),
                            ("leader_transferred", "Leader Transferred"),
                        ],
                        max_length=30,
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="activity_logs", to="clans.clan"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["clan", "-created_at"], name="clans_clana_clan_id_fa6194_idx")],
            },
        ),
        migrations.CreateModel(
            name="ClanInvitation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "clan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invitations", to="clans.clan"
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_clan_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clan_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["invited_user", "status", "-created_at"], name="clans_clani_invited_68d935_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClanJoinRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("message", models.TextField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("accepted", "Accepted"), ("declined", "Declined")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="join_requests", to="clans.clan"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clan_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["clan", "status", "-created_at"], name="clans_clanj_clan_id_c14422_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ClanMembership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("leader", "Leader"),
                            ("officer", "Officer"),
                            ("member", "Member"),
                            ("recruit", "Recruit"),
                        ],
                        default="recruit",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("contributions_gold", models.PositiveIntegerField(default=0)),
                (
                    "clan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="clans.clan"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clan_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("clan", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="clanwar",
            index=models.Index(fields=["status", "-created_at"], name="clans_clanw_status_476577_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="clanwarparticipant",
            unique_together={("war", "user")},
        ),
    ]
