# Generated by Django 6.0.3 on 2026-03-26 14:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0008_deck_is_editable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GemPackage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("gems", models.PositiveIntegerField()),
                ("bonus_gems", models.PositiveIntegerField(default=0)),
                ("price_cents", models.PositiveIntegerField(help_text="Price in smallest currency unit (e.g. cents)")),
                ("currency", models.CharField(default="usd", max_length=3)),
                (
                    "stripe_price_id",
                    models.CharField(blank=True, help_text="Optional pre-created Stripe Price ID", max_length=100),
                ),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "price_cents"],
            },
        ),
        migrations.CreateModel(
            name="GemTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("amount", models.IntegerField(help_text="Positive = credit, negative = debit")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("purchase", "Gem Purchase"),
                            ("shop_buy", "Shop Purchase"),
                            ("crate_key", "Crate Key Purchase"),
                            ("refund", "Refund"),
                            ("admin", "Admin Adjustment"),
                            ("gift", "Gift / Promotional"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, help_text="PurchaseOrder or ShopPurchase ID", max_length=200),
                ),
                ("balance_after", models.PositiveIntegerField()),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gem_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GemWallet",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("gems", models.PositiveIntegerField(default=0)),
                ("total_purchased", models.PositiveIntegerField(default=0)),
                ("total_spent", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gem_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("gems_credited", models.PositiveIntegerField(default=0)),
                ("price_cents", models.PositiveIntegerField()),
                ("currency", models.CharField(default="usd", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("stripe_checkout_session_id", models.CharField(db_index=True, max_length=200, unique=True)),
                ("stripe_payment_intent_id", models.CharField(blank=True, max_length=200)),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gem_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="orders", to="payments.gempackage"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShopItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("gem_price", models.PositiveIntegerField()),
                (
                    "original_gem_price",
                    models.PositiveIntegerField(
                        blank=True, help_text="Show crossed-out price for discounts", null=True
                    ),
                ),
                (
                    "shop_category",
                    models.CharField(
                        choices=[
                            ("featured", "Featured"),
                            ("daily_deal", "Daily Deal"),
                            ("keys", "Keys"),
                            ("cosmetics", "Cosmetics"),
                            ("convenience", "Convenience"),
                        ],
                        default="cosmetics",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, help_text="How many of the item you get per purchase"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("available_from", models.DateTimeField(blank=True, null=True)),
                ("available_until", models.DateTimeField(blank=True, null=True)),
                (
                    "max_purchases_per_user",
                    models.PositiveIntegerField(blank=True, help_text="None = unlimited", null=True),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="shop_listings", to="inventory.item"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShopPurchase",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("gems_spent", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_purchases",
                        to="inventory.iteminstance",
                    ),
                ),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="inventory.item")),
                (
                    "shop_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="purchases", to="payments.shopitem"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
