# Generated by Django 6.0.3 on 2026-03-14 10:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matchmaking", "0003_match_is_tutorial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "item categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("material", "Material"),
                            ("blueprint_building", "Blueprint: Building"),
                            ("blueprint_unit", "Blueprint: Unit"),
                            ("ability_scroll", "Ability Scroll"),
                            ("boost", "Boost"),
                            ("crate", "Crate"),
                            ("key", "Key"),
                            ("cosmetic", "Cosmetic"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=100)),
                (
                    "asset_key",
                    models.CharField(blank=True, help_text="Frontend asset key for rendering", max_length=100),
                ),
                ("is_stackable", models.BooleanField(default=True)),
                ("is_tradeable", models.BooleanField(default=True)),
                ("is_consumable", models.BooleanField(default=False, help_text="Destroyed on use (boosts, scrolls)")),
                ("max_stack", models.PositiveIntegerField(default=999)),
                ("base_value", models.PositiveIntegerField(default=0, help_text="Base gold value for bot pricing")),
                (
                    "crate_loot_table",
                    models.JSONField(
                        blank=True,
                        help_text="For crates only: list of {item_slug, weight, min_qty, max_qty}",
                        null=True,
                    ),
                ),
                (
                    "boost_params",
                    models.JSONField(
                        blank=True, help_text="For boosts: {effect_type, value, duration_ticks}", null=True
                    ),
                ),
                (
                    "blueprint_ref",
                    models.CharField(
                        blank=True,
                        help_text="For blueprints: slug of the BuildingType or UnitType this unlocks",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opens_crate",
                    models.ForeignKey(
                        blank=True,
                        help_text="For keys only: which crate item this key opens",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_by_keys",
                        to="inventory.item",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="inventory.itemcategory"
                    ),
                ),
            ],
            options={
                "ordering": ["category__order", "rarity", "name"],
            },
        ),
        migrations.CreateModel(
            name="ItemDrop",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("match_reward", "Match Reward"),
                            ("crate_open", "Crate Open"),
                            ("crafting", "Crafting"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="drops", to="inventory.item"
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="item_drops",
                        to="matchmaking.match",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_drops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("gold", models.PositiveIntegerField(default=0)),
                ("total_earned", models.PositiveIntegerField(default=0)),
                ("total_spent", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="wallet", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInventory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("acquired_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="in_inventories", to="inventory.item"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["item__category__order", "item__rarity", "item__name"],
                "unique_together": {("user", "item")},
            },
        ),
    ]
