# Generated by Django 6.0.3 on 2026-03-14 19:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
        ("inventory", "0003_item_level_alter_item_item_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="cosmetic_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Asset file delivered by this cosmetic item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cosmetic_items",
                to="assets.gameasset",
            ),
        ),
        migrations.CreateModel(
            name="EquippedCosmetic",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("slot", models.CharField(help_text="Asset key slot, e.g. infantry, barracks", max_length=100)),
                ("equipped_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        limit_choices_to={"item_type": "cosmetic"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipped_by",
                        to="inventory.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipped_cosmetics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["slot"],
                "unique_together": {("user", "slot")},
            },
        ),
    ]
