# Generated by Django 6.0.3 on 2026-03-14 22:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_item_cosmetic_params"),
        ("matchmaking", "0005_matchplayer_cosmetic_snapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemInstance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "pattern_seed",
                    models.PositiveIntegerField(default=0, help_text="0-999, determines visual variation"),
                ),
                ("wear", models.FloatField(default=0.0, help_text="0.0 = Factory New, 1.0 = Battle-Scarred")),
                ("stattrak", models.BooleanField(default=False)),
                ("stattrak_matches", models.PositiveIntegerField(default=0)),
                (
                    "stattrak_kills",
                    models.PositiveIntegerField(default=0, help_text="Regions conquered with this item equipped"),
                ),
                ("stattrak_units_produced", models.PositiveIntegerField(default=0)),
                ("nametag", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crafted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crafted_instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dropped_from_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dropped_instances",
                        to="matchmaking.match",
                    ),
                ),
                (
                    "first_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="first_owned_instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="instances", to="inventory.item"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="item_instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="deckitem",
            name="instance",
            field=models.ForeignKey(
                blank=True,
                help_text="For non-stackable items: the specific instance in this slot",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_decks",
                to="inventory.iteminstance",
            ),
        ),
        migrations.AddField(
            model_name="equippedcosmetic",
            name="instance",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific instance equipped in this slot",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipped_as",
                to="inventory.iteminstance",
            ),
        ),
        migrations.AddField(
            model_name="itemdrop",
            name="instance",
            field=models.ForeignKey(
                blank=True,
                help_text="For non-stackable drops: the specific instance that dropped",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drop_records",
                to="inventory.iteminstance",
            ),
        ),
        migrations.AddIndex(
            model_name="iteminstance",
            index=models.Index(fields=["owner"], name="inventory_i_owner_i_476278_idx"),
        ),
        migrations.AddIndex(
            model_name="iteminstance",
            index=models.Index(fields=["item"], name="inventory_i_item_id_422585_idx"),
        ),
        migrations.AddIndex(
            model_name="iteminstance",
            index=models.Index(fields=["owner", "item"], name="inventory_i_owner_i_91be12_idx"),
        ),
    ]
