# Generated by Django 6.0.3 on 2026-03-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_cosmetic_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="is_editable",
            field=models.BooleanField(default=True),
        ),
    ]
