# Generated by Django 6.0.3 on 2026-03-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_match_game_mode_matchqueue_game_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
