# Generated by Django 6.0.3 on 2026-03-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0008_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobbyplayer',
            name='team_label',
            field=models.CharField(blank=True, help_text='Team identifier for team-based modes (e.g. "challenger", "defender"). Null for free-for-all.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='team_label',
            field=models.CharField(blank=True, help_text='Team identifier for team-based modes (e.g. "challenger", "defender"). Null for free-for-all.', max_length=32, null=True),
        ),
    ]
