# Generated by Django 6.0.3 on 2026-03-29 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("developers", "0005_deviceauthorizationcode"),
        ("matchmaking", "0009_add_team_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="server",
            field=models.ForeignKey(
                blank=True,
                help_text="Gamenode server that ran this match (null = legacy inline)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches",
                to="developers.communityserver",
            ),
        ),
    ]
