# Generated by Django 6.0.3 on 2026-04-01 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0007_alter_pluginreview_rating"),
        ("matchmaking", "0010_match_server_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="lobby",
            name="server",
            field=models.ForeignKey(
                blank=True,
                help_text="Community server this lobby belongs to (null = global matchmaking)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lobbies",
                to="developers.communityserver",
            ),
        ),
    ]
