# Generated by Django 6.0.3 on 2026-03-14 18:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameAsset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "key",
                    models.SlugField(
                        help_text="Unique key to reference this asset (e.g. matches asset_key in game config)",
                        max_length=150,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("building", "Building"),
                            ("unit", "Unit"),
                            ("ability", "Ability"),
                            ("music", "Music"),
                            ("sound", "Sound Effect"),
                            ("icon", "Icon"),
                            ("texture", "Texture"),
                            ("animation", "Animation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="game_assets/")),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Game Asset",
                "verbose_name_plural": "Game Assets",
                "ordering": ["category", "name"],
            },
        ),
    ]
