"""Registry of all frontend asset keys that can be overridden via GameAsset."""

WELL_KNOWN_ASSETS = [
    # Buildings
    ("building", "port", "Navy port building"),
    ("building", "barracks", "Barracks building"),
    ("building", "carrier", "Airport/carrier building"),
    ("building", "radar", "Power plant/radar building"),
    ("building", "tower", "Sentry tower building"),
    ("building", "factory", "Ironworks/factory building"),
    ("building", "airport", "Airport building"),
    ("building", "navy_port", "Navy port building"),
    ("building", "power_plant", "Power plant building"),
    ("building", "military_base", "Military base building"),
    ("building", "ironworks", "Ironworks building"),
    ("building", "mine", "Mine building"),
    # Units
    ("unit", "ground_unit", "Infantry ground unit"),
    ("unit", "ground_unit_sphere", "Tank/sphere ground unit"),
    ("unit", "ship_1", "Ship unit"),
    ("unit", "bomber", "Air unit (bomber)"),
    ("unit", "moving", "Unit moving state icon"),
    ("unit", "nuke_rocket", "Nuke rocket icon"),
    ("unit", "capital_star", "Capital city marker"),
    ("unit", "cursor", "Selected region marker"),
    ("unit", "moving_border", "Target region marker"),
    ("unit", "plane_tag", "Plane action tag"),
    # Abilities (these also come from game_config asset_key)
    ("ability", "ab_province_nuke", "Nuke ability icon"),
    ("ability", "ab_virus", "Virus ability icon"),
    ("ability", "ab_shield", "Shield ability icon"),
    ("ability", "ab_pr_submarine", "Submarine ability icon"),
    ("ability", "ab_conscription_point", "Conscription ability icon"),
    # Icons
    ("icon", "icon_close", "Close action icon"),
    ("icon", "icon_building", "Build action icon"),
    ("icon", "icon_hex", "Players action icon"),
    ("icon", "icon_attack", "Attack action icon"),
    ("icon", "icon_storage", "Storage/resource icon"),
    ("icon", "icon_time", "Time icon"),
    ("icon", "icon_shield", "Defense action shield icon"),
    ("icon", "icon_arrow", "Move action arrow icon"),
    ("icon", "icon_coin", "Currency/coin icon"),
    ("icon", "icon_world", "World/globe icon"),
    # Textures
    ("texture", "map_coast", "Coast map texture"),
    ("texture", "hex_bg_tile", "Hexagon background tile"),
    # Audio - Music
    ("music", "music_marching", "Marching music loop"),
    ("music", "music_soviet", "Soviet March music loop"),
    ("music", "music_no_action", "No Action music"),
    ("music", "music_lofi", "Lofi music loop"),
    ("music", "music_no_action_ac", "Acoustic music"),
    ("music", "music_discorock", "Disco Rock music"),
    ("music", "music_firstsong", "First Song music"),
    ("music", "music_johny_home", "When Johnny Comes Home music"),
    # Audio - GUI
    ("sound", "sfx_button_click", "Button click sound"),
    ("sound", "sfx_click2", "Click alternate sound"),
    ("sound", "sfx_tab_click", "Tab click sound"),
    ("sound", "sfx_message_alert", "Message alert sound"),
    ("sound", "sfx_popup", "Popup notification sound"),
    # Audio - Game Effects
    ("sound", "sfx_building", "Building construction sound"),
    ("sound", "sfx_plane_start", "Plane startup sound"),
    ("sound", "sfx_plane_detected", "Plane detected sound"),
    ("sound", "sfx_fail", "Failure sound"),
    ("sound", "sfx_buzzer", "Buzzer sound"),
    ("sound", "sfx_missile_explosion", "Missile explosion sound"),
    ("sound", "sfx_nuke", "Nuke ability sound"),
    ("sound", "sfx_nuke_2", "Nuke explosion sound"),
    ("sound", "sfx_virus", "Virus ability sound"),
    ("sound", "sfx_submarine", "Submarine ability sound"),
    ("sound", "sfx_shield", "Shield ability sound"),
    ("sound", "sfx_quick_gain", "Quick gain ability sound"),
    # UI elements
    ("other", "login_top", "Login screen top decoration"),
    ("other", "login_bottom", "Login screen bottom decoration"),
    ("other", "plag_games_logo", "Plag Games logo"),
    ("other", "rank_10", "Rank 10 badge"),
    ("other", "match_circle", "Matchmaking circular UI element"),
    ("other", "match_finish_1", "Match finish UI element 1"),
    ("other", "match_finish_2", "Match finish UI element 2"),
    ("other", "match_finish_3", "Match finish UI element 3"),
]
