# Generated by Django 6.0.3 on 2026-03-29 19:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("developers", "0003_communityserver"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(max_length=50)),
                ("wasm_blob", models.FileField(blank=True, upload_to="plugins/")),
                ("wasm_hash", models.CharField(blank=True, max_length=128)),
                ("hooks", models.JSONField(default=list)),
                ("is_published", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugins",
                        to="developers.developerapp",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PluginVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.CharField(max_length=50)),
                ("wasm_blob", models.FileField(upload_to="plugins/versions/")),
                ("wasm_hash", models.CharField(max_length=128)),
                ("changelog", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="developers.plugin"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("plugin", "version")},
            },
        ),
    ]
