# Generated by Django 6.0.3 on 2026-03-31 23:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0005_deviceauthorizationcode"),
        ("game_config", "0035_seed_clan_war_game_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="communityserver",
            name="allow_custom_game_modes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="communityserver",
            name="allow_spectators",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="communityserver",
            name="allowed_game_modes",
            field=models.ManyToManyField(
                blank=True, related_name="allowed_on_servers", to="game_config.gamemode"
            ),
        ),
        migrations.AddField(
            model_name="communityserver",
            name="auto_start_match",
            field=models.BooleanField(
                default=True, help_text="Auto-start match when enough players join"
            ),
        ),
        migrations.AddField(
            model_name="communityserver",
            name="connect_url",
            field=models.URLField(
                blank=True,
                help_text="WebSocket URL for direct connection",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="communityserver",
            name="current_match_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="communityserver",
            name="current_player_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="communityserver",
            name="default_game_mode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_servers",
                to="game_config.gamemode",
            ),
        ),
        migrations.AddField(
            model_name="communityserver",
            name="match_start_countdown_seconds",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="communityserver",
            name="max_concurrent_matches",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Maximum matches running simultaneously on this server",
            ),
        ),
        migrations.AddField(
            model_name="communityserver",
            name="max_spectators",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="communityserver",
            name="min_players_to_start",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="communityserver",
            name="motd",
            field=models.TextField(
                blank=True, help_text="Message of the day shown to players on join"
            ),
        ),
        migrations.AddField(
            model_name="communityserver",
            name="password_hash",
            field=models.CharField(
                blank=True, help_text="Empty = no password required", max_length=128
            ),
        ),
        migrations.AddField(
            model_name="communityserver",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Server tags for filtering, e.g. ["competitive", "casual"]',
            ),
        ),
        migrations.AddField(
            model_name="plugin",
            name="banner",
            field=models.ImageField(blank=True, upload_to="plugins/banners/"),
        ),
        migrations.AddField(
            model_name="plugin",
            name="category",
            field=models.CharField(
                choices=[
                    ("gameplay", "Gameplay"),
                    ("economy", "Economy"),
                    ("combat", "Combat"),
                    ("admin", "Administration"),
                    ("chat", "Chat & Communication"),
                    ("anticheat", "Anti-Cheat"),
                    ("cosmetic", "Cosmetics & Visual"),
                    ("stats", "Statistics & Analytics"),
                    ("moderation", "Moderation"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="plugin",
            name="config_schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON Schema for plugin configuration",
            ),
        ),
        migrations.AddField(
            model_name="plugin",
            name="default_config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Default configuration values"
            ),
        ),
        migrations.AddField(
            model_name="plugin",
            name="deprecation_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="plugin",
            name="homepage_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="plugin",
            name="icon",
            field=models.ImageField(blank=True, upload_to="plugins/icons/"),
        ),
        migrations.AddField(
            model_name="plugin",
            name="install_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plugin",
            name="is_deprecated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plugin",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plugin",
            name="license",
            field=models.CharField(blank=True, default="MIT", max_length=100),
        ),
        migrations.AddField(
            model_name="plugin",
            name="long_description",
            field=models.TextField(
                blank=True, help_text="Full markdown description for marketplace page"
            ),
        ),
        migrations.AddField(
            model_name="plugin",
            name="min_engine_version",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="plugin",
            name="rating_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plugin",
            name="rating_sum",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plugin",
            name="required_permissions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="plugin",
            name="source_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="plugin",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="pluginversion",
            name="is_yanked",
            field=models.BooleanField(
                default=False, help_text="Yanked versions cannot be installed"
            ),
        ),
        migrations.AddField(
            model_name="pluginversion",
            name="min_engine_version",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name="ServerPlayerSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_sessions",
                        to="developers.communityserver",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomGameMode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji icon for the game mode",
                        max_length=10,
                    ),
                ),
                (
                    "config_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='JSON overrides for GameMode fields, e.g. {"max_players": 8, "tick_interval_ms": 500}',
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Visible in server browser"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("play_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_game_mode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_custom_modes",
                        to="game_config.gamemode",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_game_modes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "required_plugins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="required_by_game_modes",
                        to="developers.plugin",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_game_modes",
                        to="developers.communityserver",
                    ),
                ),
            ],
            options={
                "ordering": ["-play_count"],
                "unique_together": {("server", "slug")},
            },
        ),
        migrations.CreateModel(
            name="PluginDependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_constraint",
                    models.CharField(
                        default="*",
                        help_text='SemVer constraint, e.g. ">=1.0.0", "^2.0", "~1.2"',
                        max_length=100,
                    ),
                ),
                ("is_optional", models.BooleanField(default=False)),
                (
                    "depends_on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependents",
                        to="developers.plugin",
                    ),
                ),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="developers.plugin",
                    ),
                ),
            ],
            options={
                "ordering": ["plugin", "depends_on"],
                "unique_together": {("plugin", "depends_on")},
            },
        ),
        migrations.CreateModel(
            name="PluginReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(help_text="Rating 1-5")),
                ("title", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="developers.plugin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("plugin", "user")},
            },
        ),
        migrations.CreateModel(
            name="ServerPlugin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Server-specific plugin configuration overrides",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Load order priority (lower = loaded first)",
                    ),
                ),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_installations",
                        to="developers.plugin",
                    ),
                ),
                (
                    "plugin_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="developers.pluginversion",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installed_plugins",
                        to="developers.communityserver",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "installed_at"],
                "unique_together": {("server", "plugin")},
            },
        ),
    ]
