# Generated by Django 6.0.3 on 2026-04-01 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0006_expand_community_servers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pluginreview",
            name="rating",
            field=models.PositiveSmallIntegerField(
                help_text="Rating 1-5",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
