#!/usr/bin/env python3
"""Generate VAPID key pair using openssl CLI and append to .env file.

No Python dependencies required — only openssl (available on any Linux/macOS).

Usage:
    python3 scripts/generate_vapid_keys.py          # writes to .env
    python3 scripts/generate_vapid_keys.py /path/.env  # writes to custom path
"""

import base64
import subprocess
import sys
import tempfile
from pathlib import Path


def run(cmd):
    result = subprocess.run(cmd, capture_output=True, check=True)
    return result.stdout


def main():
    env_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parent.parent / ".env"

    with tempfile.NamedTemporaryFile(suffix=".pem") as tmp:
        # Generate EC private key (P-256 / prime256v1)
        run(["openssl", "ecparam", "-genkey", "-noout", "-name", "prime256v1", "-out", tmp.name])

        # Convert to PKCS8 PEM (what pywebpush expects)
        priv_pem = run(["openssl", "pkcs8", "-topk8", "-nocrypt", "-in", tmp.name]).decode()

        # Extract uncompressed public key point (65 bytes: 04 + x + y)
        pub_der = run(["openssl", "ec", "-in", tmp.name, "-pubout", "-outform", "DER"])

    # The last 65 bytes of the DER output are the uncompressed point
    pub_point = pub_der[-65:]
    pub_b64 = base64.urlsafe_b64encode(pub_point).decode().rstrip("=")

    # Single-line PEM for .env
    priv_escaped = priv_pem.strip().replace("\n", "\\n")

    lines = [
        "",
        "# Push notifications (VAPID) — generated by scripts/generate_vapid_keys.py",
        f"VAPID_PUBLIC_KEY={pub_b64}",
        f'VAPID_PRIVATE_KEY="{priv_escaped}"',
        "VAPID_MAILTO=mailto:admin@zelqor.com",
        "",
    ]

    # Remove existing VAPID entries if present
    if env_path.exists():
        existing = env_path.read_text()
        filtered = []
        skip = False
        for line in existing.splitlines():
            if line.startswith("VAPID_") or line.startswith("# Push notifications (VAPID)"):
                skip = True
                continue
            if skip and line.strip() == "":
                skip = False
                continue
            skip = False
            filtered.append(line)
        env_path.write_text("\n".join(filtered).rstrip("\n") + "\n")

    with open(env_path, "a") as f:
        f.write("\n".join(lines))

    print(f"VAPID keys written to {env_path}")
    print(f"Public key: {pub_b64}")


if __name__ == "__main__":
    main()
