#!/usr/bin/env python3
"""Generate a production .env file with all secrets auto-generated.

No Python dependencies required — only openssl and python3.

Usage:
    python3 scripts/generate_prod_env.py                    # writes to .env.prod
    python3 scripts/generate_prod_env.py /path/to/.env      # custom path
    python3 scripts/generate_prod_env.py --domain zelqor.pl  # set domain
"""

import base64
import os
import secrets
import subprocess
import sys
import tempfile
from pathlib import Path


def generate_django_secret(length=50):
    chars = "abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)"
    return "".join(secrets.choice(chars) for _ in range(length))


def generate_db_password(length=32):
    return secrets.token_urlsafe(length)


def generate_internal_secret(length=64):
    return secrets.token_hex(length // 2)


def generate_livekit_keys():
    return secrets.token_urlsafe(16), secrets.token_urlsafe(32)


def generate_vapid_keys():
    with tempfile.NamedTemporaryFile(suffix=".pem") as tmp:
        subprocess.run(
            ["openssl", "ecparam", "-genkey", "-noout", "-name", "prime256v1", "-out", tmp.name],
            capture_output=True,
            check=True,
        )
        priv_pem = subprocess.run(
            ["openssl", "pkcs8", "-topk8", "-nocrypt", "-in", tmp.name],
            capture_output=True,
            check=True,
        ).stdout.decode()
        pub_der = subprocess.run(
            ["openssl", "ec", "-in", tmp.name, "-pubout", "-outform", "DER"],
            capture_output=True,
            check=True,
        ).stdout

    pub_point = pub_der[-65:]
    pub_b64 = base64.urlsafe_b64encode(pub_point).decode().rstrip("=")
    priv_escaped = priv_pem.strip().replace("\n", "\\n")
    return pub_b64, priv_escaped


def main():
    env_path = Path(".env.prod")
    domain = ""

    args = sys.argv[1:]
    i = 0
    while i < len(args):
        if args[i] == "--domain" and i + 1 < len(args):
            domain = args[i + 1]
            i += 2
        else:
            env_path = Path(args[i])
            i += 1

    if not domain:
        domain = input("Podaj domenę (np. zelqor.pl): ").strip()

    print(f"Generowanie secretów dla {domain}...")

    secret_key = generate_django_secret()
    db_password = generate_db_password()
    internal_secret = generate_internal_secret()
    livekit_key, livekit_secret = generate_livekit_keys()
    vapid_pub, vapid_priv = generate_vapid_keys()

    env_content = f"""# ═══════════════════════════════════════════════════════════
# Zelqor Production Environment
# Generated by scripts/generate_prod_env.py
# Domain: {domain}
# ═══════════════════════════════════════════════════════════

# Django
SECRET_KEY={secret_key}
DEBUG=False
ALLOWED_HOSTS={domain},www.{domain}
CSRF_TRUSTED_ORIGINS=https://{domain},https://www.{domain}
CORS_ALLOWED_ORIGINS=https://{domain},https://www.{domain}

# Database (PostgreSQL + PostGIS)
DB_NAME=zelqor
DB_USER=zelqor
DB_PASSWORD={db_password}
DB_HOST=db
DB_PORT=5432

# Redis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_GAME_DB=1
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/0

# JWT
JWT_ACCESS_TOKEN_LIFETIME_MINUTES=60
JWT_REFRESH_TOKEN_LIFETIME_DAYS=7

# Internal API (Django <-> Rust Gateway)
INTERNAL_SECRET={internal_secret}

# LiveKit (voice chat)
LIVEKIT_URL=ws://livekit:7880
LIVEKIT_PUBLIC_URL=wss://{domain}/livekit
LIVEKIT_API_KEY={livekit_key}
LIVEKIT_API_SECRET={livekit_secret}

# Push notifications (VAPID)
VAPID_PUBLIC_KEY={vapid_pub}
VAPID_PRIVATE_KEY="{vapid_priv}"
VAPID_MAILTO=mailto:admin@{domain}
"""

    env_path.write_text(env_content)
    os.chmod(env_path, 0o600)

    print(f"""
Plik {env_path} wygenerowany.

Wygenerowane secrety:
  SECRET_KEY        — Django secret key
  DB_PASSWORD       — hasło do PostgreSQL
  INTERNAL_SECRET   — komunikacja Gateway <-> Django
  LIVEKIT_API_KEY   — LiveKit auth
  LIVEKIT_API_SECRET— LiveKit auth
  VAPID keys        — push notifications

Użycie:
  cp {env_path} .env
  docker compose up -d

UWAGA: Plik ma uprawnienia 600 (tylko właściciel).
        Nie commituj go do repo!
""")


if __name__ == "__main__":
    main()
