extends Node
class_name GeneralsList


const assets = {
	"GENERAL_1": "res://assets/generals/general_1.webp",
	"GENERAL_2": "res://assets/generals/general_2.webp",
	"GENERAL_3": "res://assets/generals/general_3.webp",
	"GENERAL_4": "res://assets/generals/general_4.webp",
	"GENERAL_5": "res://assets/generals/general_5.webp",
	"GENERAL_6": "res://assets/generals/general_6.webp",
	"GENERAL_7": "res://assets/generals/general_7.webp",
	"GENERAL_8": "res://assets/generals/general_8.webp",
	"GENERAL_9": "res://assets/generals/general_9.webp",
	"GENERAL_10": "res://assets/generals/general_10.webp",
	"GENERAL_11": "res://assets/generals/general_11.webp",
	"DURGA_TANDON": "res://assets/generals/general_12.webp",
	"GONG_QI": "res://assets/generals/general_13.webp",
	"GENERAL_14": "res://assets/generals/general_14.webp",
	"GENERAL_15": "res://assets/generals/general_15.webp",
	"GENERAL_16": "res://assets/generals/general_16.webp",
	"GENERAL_17": "res://assets/generals/general_17.webp",
	"GENERAL_18": "res://assets/generals/general_18.webp",
	"GENERAL_19": "res://assets/generals/general_19.webp",
	"GENERAL_20": "res://assets/generals/general_20.webp",
	"GENERAL_21": "res://assets/generals/general_21.webp",
	"GENERAL_22": "res://assets/generals/general_22.webp",
	"GENERAL_23": "res://assets/generals/general_23.webp",
	"GENERAL_24": "res://assets/generals/general_24.webp",
	"GENERAL_25": "res://assets/generals/general_25.webp",
	"GENERAL_26": "res://assets/generals/general_26.webp",
	"GENERAL_27": "res://assets/generals/general_27.webp",
	"GENERAL_28": "res://assets/generals/general_28.webp",
	"GENERAL_29": "res://assets/generals/general_29.webp",
	"GENERAL_30": "res://assets/generals/general_30.webp",
	"GENERAL_31": "res://assets/generals/general_31.webp",
	"GENERAL_32": "res://assets/generals/general_32.webp",
	"GENERAL_33": "res://assets/generals/general_33.webp",
	"GENERAL_34": "res://assets/generals/general_34.webp",
	"GENERAL_35": "res://assets/generals/general_35.webp",
	"GENERAL_36": "res://assets/generals/general_36.webp",
	"GENERAL_37": "res://assets/generals/general_37.webp",
	"GENERAL_38": "res://assets/generals/general_38.webp",
	"GENERAL_39": "res://assets/generals/general_39.webp",
	"GENERAL_40": "res://assets/generals/general_40.webp",
	"GENERAL_41": "res://assets/generals/general_41.webp",
	"GENERAL_42": "res://assets/generals/general_42.webp",
	"GENERAL_43": "res://assets/generals/general_43.webp",
	"GENERAL_44": "res://assets/generals/general_44.webp",
	"GENERAL_45": "res://assets/generals/general_45.webp",
	"GENERAL_TOMEK": "res://assets/generals/generla_tomek_2.webp",
	"GENERAL_46": "res://assets/generals/general_pilsudski.webp",
	"GENERAL_47": "res://assets/generals/general_stalin.webp",
	"GENERAL_48": "res://assets/generals/general_lincoln.webp",
	"GENERAL_49": "res://assets/generals/general_churchill.webp",
	"GENERAL_50": "res://assets/generals/general_castro.webp",
	"GENERAL_51": "res://assets/generals/general_zedong.webp",
	"GENERAL_52": "res://assets/generals/general_gandi.webp",
	"GENERAL_53": "res://assets/generals/general_wilson.webp",
	"GENERAL_54": "res://assets/generals/general_mustafa.webp",
	"GENERAL_55": "res://assets/generals/general_hirohito.webp",
	"GENERAL_56": "res://assets/generals/general_bismarck.webp",
	"GENERAL_57": "res://assets/generals/general_maplord_2.webp",
	"MAPLORD_GOLD": "res://assets/generals/general_maplord_2_gold.webp",
	"GENERAL_58": "res://assets/generals/general_58.webp",
}

static func get_asset_texture_path_by_name(name : String):
	if assets.has(name):
		return assets[name]
	else: 
		return assets["DURGA_TANDON"]
