# Generated by Django 6.0.3 on 2026-03-10 20:47

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=3, unique=True)),
                ("geometry", django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                "verbose_name_plural": "countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("geometry", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ("centroid", django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ("is_coastal", models.BooleanField(default=False)),
                ("population_weight", models.FloatField(default=1.0, help_text="Weight for unit generation rate")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="regions", to="geo.country"
                    ),
                ),
                ("neighbors", models.ManyToManyField(blank=True, to="geo.region")),
            ],
            options={
                "ordering": ["country__name", "name"],
            },
        ),
    ]
