# Generated by Django 6.0.3 on 2026-03-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_region_map_source_id_region_sea_distances'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='border_tiles',
            field=models.JSONField(blank=True, default=list, help_text='Border tile positions'),
        ),
        migrations.AddField(
            model_name='region',
            name='buildings_data',
            field=models.JSONField(blank=True, default=dict, help_text='Building placement data from source map'),
        ),
        migrations.AddField(
            model_name='region',
            name='capital_data',
            field=models.JSONField(blank=True, default=dict, help_text='Capital position and UI data'),
        ),
        migrations.AddField(
            model_name='region',
            name='centroid_game',
            field=models.JSONField(blank=True, default=list, help_text='Centroid [x, y] in game pixel coords'),
        ),
        migrations.AddField(
            model_name='region',
            name='coast_port_tile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='region',
            name='e_points',
            field=models.IntegerField(default=0, help_text='Economy/energy points'),
        ),
        migrations.AddField(
            model_name='region',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='region',
            name='is_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='region',
            name='polygons_data',
            field=models.JSONField(blank=True, default=list, help_text='Polygon rings in game pixel coords: [{"name": ..., "points": [...]}, ...]'),
        ),
        migrations.AddField(
            model_name='region',
            name='tile_chunks',
            field=models.JSONField(blank=True, default=list, help_text='Texture chunk coords: ["cx,cy", ...]'),
        ),
        migrations.AddField(
            model_name='region',
            name='tiles',
            field=models.JSONField(blank=True, default=list, help_text='Grid tile positions: ["x,y", ...]'),
        ),
    ]
