# Generated by Django 6.0.3 on 2026-03-10 20:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameStateSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tick", models.PositiveIntegerField()),
                ("state_data", models.JSONField(help_text="Full game state snapshot (regions, players, buildings)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["match", "tick"],
            },
        ),
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("total_ticks", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-match__created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlayerResult",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("placement", models.PositiveIntegerField(default=0, help_text="1=winner, 2=second, etc.")),
                ("regions_conquered", models.PositiveIntegerField(default=0)),
                ("units_produced", models.PositiveIntegerField(default=0)),
                ("units_lost", models.PositiveIntegerField(default=0)),
                ("buildings_built", models.PositiveIntegerField(default=0)),
                ("elo_change", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["placement"],
            },
        ),
    ]
